version: '3.3'

services:
  db:
    image: mongo:4.4

  laptop-service:
    build: ./laptop
    volumes:
      - ./laptop:/usr/src/app
    ports:
      - "5001:80"
    environment:
      - DB_PORT_27017_TCP_ADDR=db
    depends_on:
      - db

  website:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - "5000:80"
    depends_on:
      - laptop-service

  brevets-calculator:
    build: ../brevets
    ports:
      - "5002:5000"
    environment:
      - DB_PORT_27017_TCP_ADDR=db
    depends_on:
      - db